# Generated by Django 5.2.14 on 2026-05-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlet',
            name='homepage_url',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='rss_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='section_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='rawarticle',
            name='url',
            field=models.URLField(max_length=1000, unique=True),
        ),
    ]
