# Generated by Django 5.2.14 on 2026-05-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0002_alter_outlet_homepage_url_alter_outlet_rss_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawarticle',
            name='ai_extracted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawarticle',
            name='ai_extraction',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
