# Generated by Django 5.2.14 on 2026-05-20 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0003_rawarticle_ai_extracted_at_rawarticle_ai_extraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='image_disclaimer',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='image_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='rawarticle',
            name='image_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
