# Generated by Django 5.2.14 on 2026-05-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0004_incident_image_disclaimer_incident_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='canonical_title_ca',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='canonical_title_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='canonical_title_es',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='image_disclaimer_ca',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='image_disclaimer_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='image_disclaimer_es',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='scoring_notes_ca',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='scoring_notes_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='scoring_notes_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='short_neutral_summary_ca',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='short_neutral_summary_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='short_neutral_summary_es',
            field=models.TextField(blank=True, null=True),
        ),
    ]
