# Generated by Django 5.2.14 on 2026-05-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0005_incident_canonical_title_ca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='thumbnail_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='rawarticle',
            name='thumbnail_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
