# Generated by Django 5.2.14 on 2026-05-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0006_incident_thumbnail_url_rawarticle_thumbnail_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawarticle',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('ignored', 'Ignored'), ('candidate', 'Candidate'), ('processed', 'Processed'), ('failed', 'Failed')], db_index=True, default='new', max_length=20),
        ),
    ]
