# Generated by Django 5.2.14 on 2026-05-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0007_alter_rawarticle_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawarticle',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('ignored', 'Ignored'), ('candidate', 'Candidate'), ('processed', 'Processed'), ('failed', 'Failed'), ('failed_ai', 'Failed AI')], db_index=True, default='new', max_length=20),
        ),
    ]
