# Generated by Django 5.2.14 on 2026-05-18 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('press', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatiricalHeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=140)),
                ('tone', models.CharField(choices=[('deportivo', 'Deportivo'), ('absurdo', 'Absurdo'), ('ironico', 'Ironico'), ('suave', 'Suave')], max_length=20)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('why_safe', models.TextField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satirical_headlines', to='press.incident')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
