# Generated by Django 5.2.14 on 2026-05-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='satiricalheadline',
            name='text_ca',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='satiricalheadline',
            name='text_en',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='satiricalheadline',
            name='text_es',
            field=models.CharField(max_length=140, null=True),
        ),
    ]
