# Generated by Django 5.2.14 on 2026-05-18 16:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(unique=True)),
                ('province', models.CharField(blank=True, max_length=120, null=True)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeagueSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='ScoringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('apunyalament', 'Apunyalament'), ('arma_blanca', 'Arma blanca'), ('homicidio', 'Homicidio'), ('robo_violento', 'Robo violento'), ('pelea', 'Pelea'), ('agresion', 'Agresion'), ('incivismo', 'Incivismo'), ('disturbios', 'Disturbios'), ('transporte_publico', 'Transporte publico'), ('otro_suceso', 'Otro suceso'), ('no_relevante', 'No relevante')], max_length=40, unique=True)),
                ('base_points', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='LeagueRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='league.leagueseason')),
            ],
            options={
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='CityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.FloatField(default=0)),
                ('incidents_count', models.PositiveIntegerField(default=0)),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='league.city')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_scores', to='league.leagueround')),
            ],
            options={
                'ordering': ['position', '-points', 'city__name'],
                'constraints': [models.UniqueConstraint(fields=('round', 'city'), name='unique_score_per_round_city')],
            },
        ),
    ]
