# Generated by Django 5.2.14 on 2026-05-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='name_ca',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='name_en',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='name_es',
            field=models.CharField(max_length=160, null=True),
        ),
    ]
