# Generated by Django 5.2.14 on 2026-05-18 16:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(unique=True)),
                ('domain', models.CharField(max_length=255)),
                ('homepage_url', models.URLField()),
                ('rss_url', models.URLField(blank=True, null=True)),
                ('section_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_title', models.CharField(max_length=500)),
                ('neighborhood', models.CharField(blank=True, max_length=160, null=True)),
                ('province', models.CharField(blank=True, max_length=120, null=True)),
                ('category', models.CharField(choices=[('apunyalament', 'Apunyalament'), ('arma_blanca', 'Arma blanca'), ('homicidio', 'Homicidio'), ('robo_violento', 'Robo violento'), ('pelea', 'Pelea'), ('agresion', 'Agresion'), ('incivismo', 'Incivismo'), ('disturbios', 'Disturbios'), ('transporte_publico', 'Transporte publico'), ('otro_suceso', 'Otro suceso'), ('no_relevante', 'No relevante')], max_length=40)),
                ('happened_at', models.DateTimeField(blank=True, null=True)),
                ('severity_1_5', models.PositiveSmallIntegerField(default=1)),
                ('confidence_0_1', models.FloatField(default=0)),
                ('points', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('duplicate', 'Duplicate')], db_index=True, default='draft', max_length=20)),
                ('short_neutral_summary', models.TextField(blank=True, null=True)),
                ('scoring_notes', models.TextField(blank=True, null=True)),
                ('mentions_police_confirmation', models.BooleanField(default=False)),
                ('mentions_other_media_as_source', models.BooleanField(default=False)),
                ('source_media_mentioned', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='league.city')),
                ('is_duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='press.incident')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RawArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('headline', models.CharField(max_length=500)),
                ('excerpt', models.TextField(blank=True, null=True)),
                ('raw_text', models.TextField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('new', 'New'), ('ignored', 'Ignored'), ('candidate', 'Candidate'), ('processed', 'Processed'), ('failed', 'Failed')], db_index=True, default='new', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_articles', to='press.outlet')),
            ],
            options={
                'ordering': ['-scraped_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='press.incident')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_sources', to='press.rawarticle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status', 'category'], name='press_incid_status_b8ca90_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['city', 'category'], name='press_incid_city_id_27730b_idx'),
        ),
        migrations.AddIndex(
            model_name='rawarticle',
            index=models.Index(fields=['status', 'scraped_at'], name='press_rawar_status_a94b9a_idx'),
        ),
        migrations.AddConstraint(
            model_name='incidentsource',
            constraint=models.UniqueConstraint(fields=('incident', 'article'), name='unique_incident_article'),
        ),
    ]
